server:
  port: 8181

spring:
  application:
    name: trackingnumber
  datasource:
    url: jdbc:h2:mem:trackingnumberdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  data:
    redis:
      host: ec2-34-224-248-27.compute-1.amazonaws.com
      port: 13520
      password: p10cf95f4bb67f3fc3ba6bcbc232a5d8212fac342a0cf998fb5e9724a3156a06f

